### ISSUE TITLE
Failed to read script

### ISSUE THREAD

**Issue by SimonPlays15** [superblaubeere27/obfuscator#104]
I got the Issue that, if I run the programm (command line or executable jar) I got the error that the script file cannot be loaded?

Error code:

`Failed to load script
java.lang.IllegalStateException: Failed to compile Script
        at me.superblaubeere27.jobf.utils.script.JObfScript.<init>(JObfScript.java:29)
        at me.superblaubeere27.jobf.JObfImpl.processJar(JObfImpl.java:223)
        at me.superblaubeere27.jobf.JObf.main(JObf.java:231)
Caused by: java.lang.NullPointerException: Cannot invoke "javax.script.ScriptEngine.eval(String)" because "this.jsEngine" is null
        at me.superblaubeere27.jobf.utils.script.JObfScript.<init>(JObfScript.java:27)
        ... 2 more`

**Comment by Skitbet** [comment]
Yea me to

**Comment by AbdoD97** [comment]
any fix for this??

**Comment by QetzDev** [comment]
This error occurred when I ran the program with Java 15, because the ScriptEngine "nashorn" is no longer implemented in JDK 15. I.e., you can try to run the jar with a Runtime 8. (But of course this can't execute higher compiled code).
