### ISSUE TITLE
this.jsEngine is null

### ISSUE THREAD

**Issue by jarnoboy404** [superblaubeere27/obfuscator#105]
# Bug Report
### Expected Behaviour
I added my input file and output file. And i clicked on obfuscate and then a error appeared in the console.
And i didn't get a output file
### Actual Behaviour
```
ERROR: Missing required option(s) [jarIn] (Tip: try --help and even if you specified a config you have to specify an input and output jar)
joptsimple.MissingRequiredOptionsException: Missing required option(s) [jarIn]
        at joptsimple.OptionParser.ensureRequiredOptions(OptionParser.java:426)
        at joptsimple.OptionParser.parse(OptionParser.java:400)
        at me.superblaubeere27.jobf.JObf.main(JObf.java:117)
Starting in GUI Mode
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.bulenkov.darcula.DarculaLaf (file:/D:/Documenten/Projects/IntelliJ/Obfuscator/obfuscator-1.9.3.jar) to field javax.swing.text.html.HTMLEditorKit.DEFAULT_STYLES_KEY
WARNING: Please consider reporting this to the maintainers of com.bulenkov.darcula.DarculaLaf
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
Failed to load script
java.lang.IllegalStateException: Failed to compile Script
        at me.superblaubeere27.jobf.utils.script.JObfScript.<init>(JObfScript.java:29)
        at me.superblaubeere27.jobf.JObfImpl.processJar(JObfImpl.java:223)
        at me.superblaubeere27.jobf.ui.GUI.lambda$startObfuscator$13(GUI.java:316)
        at java.base/java.lang.Thread.run(Thread.java:832)
Caused by: java.lang.NullPointerException: Cannot invoke "javax.script.ScriptEngine.eval(String)" because "this.jsEngine" is null
        at me.superblaubeere27.jobf.utils.script.JObfScript.<init>(JObfScript.java:27)
        ... 3 more
```
### How to reproduce the behaviour
Maybe there is a setting wrong in my configuration? Or there is a error in your code.

### Config
```
{
  "input": "D:\\Documenten\\Minecraft\\Custom Servers\\TestServer 1.16.4\\plugins\\RowParser.jar",
  "output": "D:\\Documenten\\Minecraft\\Custom Servers\\TestServer 1.16.4\\plugins\\RowParser2.jar",
  "script": "function isRemappingEnabledForClass(node) {\n    return false;\n}\nfunction isObfuscatorEnabledForClass(node) {\n    return true;\n}",
  "libraries": [],
  "Crasher": {
    "Enabled": false
  },
  "InvokeDynamic": {
    "Enabled": false
  },
  "HWIDPRotection": {
    "Enabled": false,
    "HWID": "399B818FE1A6F69B2C600FE5CAC29361"
  },
  "Optimizer": {
    "Enabled": false,
    "Replace String.equals()": false,
    "Replace String.equalsIgnoreCase()": false,
    "Optimize static string calls": false
  },
  "LineNumberRemover": {
    "Enabled": true,
    "Rename local variables": true,
    "Remove Line Numbers": true,
    "Remove Debug Names": true,
    "Add Local Variables": true,
    "New SourceFile Name": ""
  },
  "StringEncryption": {
    "Enabled": true,
    "HideStrings": false,
    "AES": false
  },
  "NumberObfuscation": {
    "Enabled": true,
    "Extract to Array": true,
    "Obfuscate Zero": true,
    "Shift": false,
    "And": false,
    "Multiple Instructions": true
  },
  "ReferenceProxy": {
    "Enabled": false
  },
  "ShuffleMembers": {
    "Enabled": true
  },
  "InnerClassRemover": {
    "Enabled": true,
    "Remap": false,
    "Remove Metadata": true
  },
  "NameObfuscation": {
    "Enabled": false
  },
  "Packager": {
    "Enabled": false,
    "Use MainClass from the JAR manifest": true,
    "Main class": "org.example.Main"
  },
  "FlowObfuscator": {
    "Enabled": true,
    "Mangle Comparisons": true,
    "Replace GOTO": true,
    "Replace If": true,
    "Bad POP": true,
    "Bad Concat": true,
    "Mangle Switches": false,
    "Mangle Return": false,
    "Mangle Local Variables": false
  },
  "HideMembers": {
    "Enabled": true
  },
  "Inlining": {
    "Enabled": false
  }
}
```

**Comment by QetzDev** [comment]
This error occurred when I ran the program with Java 15, because the ScriptEngine "nashorn" is no longer implemented in JDK 15. I.e., you can try to run the jar with a Runtime 8. (But of course this can't execute higher compiled code).
