### ISSUE TITLE
MissingClassException while trying to obfuscate

### ISSUE THREAD

**Issue by vishva-javis** [superblaubeere27/obfuscator#112]
me.superblaubeere27.jobf.utils.MissingClassException: java/lang/Object (referenced in org/springframework/boot/loader/jar/CentralDirectoryVisitor) is missing in the classPath.
	at me.superblaubeere27.jobf.JObfImpl.buildHierarchy(JObfImpl.java:140)
	at me.superblaubeere27.jobf.processors.name.NameObfuscation.transformPost(NameObfuscation.java:115)
	at me.superblaubeere27.jobf.JObfImpl.processJar(JObfImpl.java:454)
	at me.superblaubeere27.jobf.ui.GUI.lambda$startObfuscator$15(GUI.java:402)
	at java.lang.Thread.run(Unknown Source)

{
  "input": "C:\\Users\\SNAPSHOT.jar",
  "output": "C:\\Users\\obf.jar",
  "script": "function isRemappingEnabledForClass(node) {\n    return true;\n}\nfunction isObfuscatorEnabledForClass(node) {\n    return true;\n}",
  "libraries": [],
  "Crasher": {
    "Enabled": false,
    "Invalid Signatures": true,
    "Empty annotation spam": true
  },
  "InvokeDynamic": {
    "Enabled": false
  },
  "HWIDPRotection": {
    "Enabled": false,
    "HWID": "905E910165DED6EBF0F5F96183FF1A79"
  },
  "Optimizer": {
    "Enabled": false,
    "Replace String.equals()": false,
    "Replace String.equalsIgnoreCase()": false,
    "Optimize static string calls": false
  },
  "LineNumberRemover": {
    "Enabled": true,
    "Rename local variables": true,
    "Remove Line Numbers": true,
    "Remove Debug Names": true,
    "Add Local Variables": true,
    "New SourceFile Name": ""
  },
  "StringEncryption": {
    "Enabled": true,
    "HideStrings": false,
    "AES": false
  },
  "NumberObfuscation": {
    "Enabled": true,
    "Extract to Array": true,
    "Obfuscate Zero": true,
    "Shift": false,
    "And": false,
    "Multiple Instructions": true
  },
  "ReferenceProxy": {
    "Enabled": false
  },
  "ShuffleMembers": {
    "Enabled": true
  },
  "InnerClassRemover": {
    "Enabled": true,
    "Remap": false,
    "Remove Metadata": true
  },
  "NameObfuscation": {
    "Enabled": true,
    "Excluded classes": "",
    "Excluded methods": "",
    "Excluded fields": "",
    "Package": true,
    "New Packages": "",
    "Accept Missing Libraries": false
  },
  "General Settings": {
    "Generator characters": "Il",
    "Custom dictionary": false,
    "Class Name dictionary": "",
    "Name dictionary": "",
    "Use STORE instead of DEFLATE (For e.g. SpringBoot)": false
  },
  "Packager": {
    "Enabled": false,
    "Use MainClass from the JAR manifest": true,
    "Main class": "org.example.Main"
  },
  "FlowObfuscator": {
    "Enabled": true,
    "Mangle Comparisons": true,
    "Replace GOTO": true,
    "Replace If": true,
    "Bad POP": true,
    "Bad Concat": true,
    "Mangle Switches": false,
    "Mangle Return": false,
    "Mangle Local Variables": false
  },
  "HideMembers": {
    "Enabled": true
  },
  "Inlining": {
    "Enabled": false
  }
}

**Comment by zecode** [comment]
1.9.3 release is broken. Try master branch.
Two distinct JObfImpl instances created.
JObf loads classpath and saves it in the first JObfImpl.
NameObfuscation tries to get classpath entries from another JObfImpl (which has empty classpath).

**Comment by 4wl** [comment]
> 1.9.3 release is broken. Try master branch.
> Two distinct JObfImpl instances created.
> JObf loads classpath and saves it in the first JObfImpl.
> NameObfuscation tries to get classpath entries from another JObfImpl (which has empty classpath).

can u add my discord to teahc me? M3dusa#9624

**Comment by JonnyOnline** [comment]
You just leaked your HWID
