### ISSUE TITLE
me.superblaubeere27.jobf.utils.MissingClassException: java/lang/Object is missing in the classPath.

### ISSUE THREAD

**Issue by nolove1337** [superblaubeere27/obfuscator#120]
me.superblaubeere27.jobf.utils.MissingClassException: java/lang/Object is missing in the classPath.
        at me.superblaubeere27.jobf.JObfImpl.buildHierarchy(JObfImpl.java:103)
        at me.superblaubeere27.jobf.processors.name.NameObfuscation.transformPost(NameObfuscation.java:62)
        at me.superblaubeere27.jobf.JObfImpl.processJar(JObfImpl.java:314)
        at me.superblaubeere27.jobf.ui.GUI.lambda$startObfuscator$13(GUI.java:316)
        at java.lang.Thread.run(Unknown Source)

**Comment by pp0236** [comment]
add `rt.jar` to classpath (jrex.x.x_xx\lib\rt.jar)

![image](https://user-images.githubusercontent.com/54238880/152491514-4b3cb905-6ac1-48bf-9889-6cce662f9ae2.png)

**Comment by bbroken776** [comment]
Hey, im having the same issue however adding rt.jar is not working ... im using a macbook m1 apple silicon
