### ISSUE TITLE
Failed to compile Script

### ISSUE THREAD

**Issue by yStreakBR** [superblaubeere27/obfuscator#129]
# Bug Report
### Expected Behaviour
Tell us what you wanted to do. If you think that everyone knows, what you expected (for example, if the program just crashed), you can skip this section
### Actual Behaviour
Tell us what happened. If there is an Exception please attach it.

Failed to load script
java.lang.IllegalStateException: Failed to compile Script
        at me.superblaubeere27.jobf.utils.script.JObfScript.<init>(JObfScript.java:29)
        at me.superblaubeere27.jobf.JObfImpl.processJar(JObfImpl.java:223)
        at me.superblaubeere27.jobf.JObf.main(JObf.java:231)
Caused by: java.lang.NullPointerException: Cannot invoke "javax.script.ScriptEngine.eval(String)" because "this.jsEngine" is null
        at me.superblaubeere27.jobf.utils.script.JObfScript.<init>(JObfScript.java:27)
        ... 2 more

### How to reproduce the behaviour
Tell us how to reproduce the wrong behaviour of the program. If it's an error which has to do this the obfuscation please **always** attach the configuration. 
(To get the config open the obfuscator in GUI-Mode, goto `Config`, enable `PrettyPrint` and press `Build`)

java -jar obfuscator.jar --jarIn zBedWars.jar --jarOut zBedWars-1.0.jar

### Possible fix
If you have no idea then you can just skip this section ^^

**Comment by Alpho320** [comment]
This is the reason: https://openjdk.java.net/jeps/372. 
You can use https://github.com/Alpho320/obfuscator.

**Comment by federicomartinlara1976** [comment]
The repository

https://github.com/Alpho320/obfuscator.

doesn't compile. It is a shit.

**Comment by Zcraft3793** [comment]
download nashorn-core from maven bro (and add it to class path)
nashorn is removed from jdk in Java 12
