### ISSUE TITLE
can't start

### ISSUE THREAD

**Issue by t0rasan20131** [superblaubeere27/obfuscator#13]
C:\Users\admin>java -jar C:\Users\admin\Desktop\obfuscator-1.71.jar
Exception in thread "main" java.lang.NullPointerException
        at java.io.FilterInputStream.read(Unknown Source)
        at sun.nio.cs.StreamDecoder.readBytes(Unknown Source)
        at sun.nio.cs.StreamDecoder.implRead(Unknown Source)
        at sun.nio.cs.StreamDecoder.read(Unknown Source)
        at java.io.InputStreamReader.read(Unknown Source)
        at java.io.BufferedReader.fill(Unknown Source)
        at java.io.BufferedReader.readLine(Unknown Source)
        at java.io.BufferedReader.readLine(Unknown Source)
        at me.superblaubeere27.jobf.utils.Templates.getResourceFiles(Templates.java:33)
        at me.superblaubeere27.jobf.utils.Templates.loadTemplates(Templates.java:17)
        at me.superblaubeere27.jobf.JObf.main(JObf.java:79)
        Suppressed: java.lang.NullPointerException
                at java.io.FilterInputStream.close(Unknown Source)
                at sun.net.www.protocol.jar.JarURLConnection$JarURLInputStream.close(Unknown Source)
                at sun.nio.cs.StreamDecoder.implClose(Unknown Source)
                at sun.nio.cs.StreamDecoder.close(Unknown Source)
                at java.io.InputStreamReader.close(Unknown Source)
                at java.io.BufferedReader.close(Unknown Source)
                at me.superblaubeere27.jobf.utils.Templates.getResourceFiles(Templates.java:36)
                ... 2 more
        Suppressed: java.lang.NullPointerException
                at java.io.FilterInputStream.close(Unknown Source)
                at sun.net.www.protocol.jar.JarURLConnection$JarURLInputStream.close(Unknown Source)
                at me.superblaubeere27.jobf.utils.Templates.getResourceFiles(Templates.java:36)
                ... 2 more

**Comment by superblaubeere27** [comment]
Well I never saw this before. Which java version?

**Comment by t0rasan20131** [comment]
C:\Users\torak>java -version
java version "1.8.0_91"
Java(TM) SE Runtime Environment (build 1.8.0_91-b15)
Java HotSpot(TM) 64-Bit Server VM (build 25.91-b15, mixed mode)

**Comment by t0rasan20131** [comment]
i can run from eclipse but i can't run jar

**Comment by superblaubeere27** [comment]
Did you build it yourself?

**Comment by t0rasan20131** [comment]
yes

**Comment by t0rasan20131** [comment]
oh
works
i updated java to 1.8.0_191

**Comment by t0rasan20131** [comment]
thanks
