### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by ghost** [superblaubeere27/obfuscator#133]
Failed to load script
java.lang.IllegalStateException: Failed to compile Script
        at me.superblaubeere27.jobf.utils.script.JObfScript.<init>(JObfScript.java:29)
        at me.superblaubeere27.jobf.JObfImpl.processJar(JObfImpl.java:223)
        at me.superblaubeere27.jobf.JObf.main(JObf.java:231)
Caused by: java.lang.NullPointerException: Cannot invoke "javax.script.ScriptEngine.eval(String)" because "this.jsEngine" is null
        at me.superblaubeere27.jobf.utils.script.JObfScript.<init>(JObfScript.java:27)
        ... 2 more

**Comment by Alpho320** [comment]
#129
