### ISSUE TITLE
Minecraft Exception in "Client Thread"

### ISSUE THREAD

**Issue by TheBlueRuby** [superblaubeere27/obfuscator#147]
## Expected behaviour:

Minecraft will boot up and load into the main menu

## Actual behaviour

Minecraft will get stuck on "not responding" on the mojang logo screen

## Extra Details

I have narrowed the issue down to this as the non-obfuscated jar runs fine

## Error log

`08:47:26.188
Version does not support log configuration, will assume one plaintext entry per line
08:47:32.794
java.lang.VerifyError: Bad type on operand stack
08:47:32.795
Exception Details:
08:47:32.795
Location:
08:47:32.795
net/minecraft/client/renderer/tileentity/TileEntityChestRenderer.renderTileEntityAt(Lnet/minecraft/tileentity/TileEntityChest;DDDFI)V @943: invokestatic
08:47:32.795
Reason: 08:47:32.835
at optifine.FieldLocatorType.getField(Unknown Source)
08:47:32.835
at optifine.ReflectorField.getTargetField(Unknown Source)
08:47:32.850
at optifine.ReflectorField.<init>(Unknown Source)
08:47:32.850
at optifine.ReflectorField.<init>(Unknown Source)
08:47:32.850
at optifine.Reflector.<clinit>(Unknown Source)
08:47:32.850
at optifine.ReflectorForge.putLaunchBlackboard(Unknown Source)
08:47:32.850
at optifine.Config.initGameSettings(Unknown Source)
08:47:32.850
at net.minecraft.client.settings.GameSettings.<init>(Unknown Source)
08:47:32.850
at net.minecraft.client.Minecraft.startGame(Unknown Source)
08:47:32.850
at net.minecraft.client.Minecraft.run(Unknown Source)
08:47:32.850
at net.minecraft.client.main.Main.main(Unknown Source)
08:47:46.669
Loading Configs!
08:47:46.692
Exception in thread "Client thread" java.lang.NullPointerException
08:47:46.692
at net.minecraft.crash.CrashReportCategory.firstTwoElementsOfStackTraceMatch(Unknown Source)
08:47:46.692
at net.minecraft.crash.CrashReport.makeCategoryDepth(Unknown Source)
08:47:46.693
at net.minecraft.crash.CrashReport.makeCategory(Unknown Source)
08:47:46.693
at net.minecraft.client.Minecraft.run(Unknown Source)
08:47:46.693
at net.minecraft.client.main.Main.main(Unknown Source)`

**Comment by TheBlueRuby** [comment]
I tried reinstalling java for something else and it works now. It must be a bug with my java installation. I was using the OpenJDK JRE 8 if it helps anyone.
