### ISSUE TITLE
GUI mode won't open (OpenJDK 8)

### ISSUE THREAD

**Issue by Dannyx1604** [superblaubeere27/obfuscator#162]
# Bug Report
### Expected Behaviour
It should open the gui by using Java 8
### Actual Behaviour
I get the following error while trying to run the program in gui mode (Java 8):
```Exception in thread "main" java.lang.ExceptionInInitializerError
	at com.bulenkov.iconloader.IconLoader.<clinit>(IconLoader.java:53)
	at com.bulenkov.darcula.DarculaLaf.getDefaults(DarculaLaf.java:97)
	at javax.swing.UIManager.setLookAndFeel(UIManager.java:539)
	at javax.swing.UIManager.setLookAndFeel(UIManager.java:583)
	at me.superblaubeere27.jobf.JObf.main(JObf.java:260)
Caused by: java.lang.NullPointerException
	at com.bulenkov.iconloader.util.UIUtil.initSystemFontData(UIUtil.java:254)
	at com.bulenkov.iconloader.util.JBUI.calculateScaleFactor(JBUI.java:47)
	at com.bulenkov.iconloader.util.JBUI.<clinit>(JBUI.java:33)
	... 5 more
```
And if I use Java 17 I also get this error:
```Caused by: java.lang.NullPointerException: Cannot invoke "java.awt.Font.getName()" because "font" is null
	at com.bulenkov.iconloader.util.UIUtil.initSystemFontData(UIUtil.java:254)
	at com.bulenkov.iconloader.util.JBUI.calculateScaleFactor(JBUI.java:47)
	at com.bulenkov.iconloader.util.JBUI.<clinit>(JBUI.java:33)
	... 5 more
```
### How to reproduce the behaviour
Use Java 8
Run it on Ubuntu 22.04
Currently no config
### Possible fix
If you have no idea then you can just skip this section ^^

**Comment by Dannyx1604** [comment]
How quickly time flies by...
Anyways, thanks but now I don't really need the help anymore xD
