### ISSUE TITLE
 Unsupported class file major version 66

### ISSUE THREAD

**Issue by Beninwende** [superblaubeere27/obfuscator#165]
I try this fork https://github.com/Alpho320/obfuscator and I always get the error bellow. I try with JDK 17, 21, 22, 23(same issue).
Can you help me please. thanks.

(base) lionel.nikiema@UNICKQJMVG9G0 Desktop % java -jar obfuscator-core-1.9.4-SNAPSHOT.jar
16:05:50,130 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback-test.xml]
16:05:50,130 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Could NOT find resource [logback.groovy]
16:05:50,130 |-INFO in ch.qos.logback.classic.LoggerContext[default] - Found resource [logback.xml] at [jar:file:/Users/lionel.nikiema/Desktop/obfuscator-core-1.9.4-SNAPSHOT.jar!/logback.xml]
16:05:50,135 |-INFO in ch.qos.logback.core.joran.spi.ConfigurationWatchList@5383967b - URL [jar:file:/Users/lionel.nikiema/Desktop/obfuscator-core-1.9.4-SNAPSHOT.jar!/logback.xml] is not of type file
16:05:50,157 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - debug attribute not set
16:05:50,157 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.core.ConsoleAppender]
16:05:50,158 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [CONSOLE]
16:05:50,160 |-INFO in ch.qos.logback.core.joran.action.NestedComplexPropertyIA - Assuming default type [ch.qos.logback.classic.encoder.PatternLayoutEncoder] for [encoder] property
16:05:50,185 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [me.superblaubeere27.jobf.ui.Appender]
16:05:50,185 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [FORM]
16:05:50,185 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - About to instantiate appender of type [ch.qos.logback.classic.AsyncAppender]
16:05:50,186 |-INFO in ch.qos.logback.core.joran.action.AppenderAction - Naming appender as [ASYNC]
16:05:50,186 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [FORM] to ch.qos.logback.classic.AsyncAppender[ASYNC]
16:05:50,186 |-INFO in ch.qos.logback.classic.AsyncAppender[ASYNC] - Attaching appender named [FORM] to AsyncAppender.
16:05:50,186 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [CONSOLE] to ch.qos.logback.classic.AsyncAppender[ASYNC]
16:05:50,186 |-WARN in ch.qos.logback.classic.AsyncAppender[ASYNC] - One and only one appender may be attached to AsyncAppender.
16:05:50,186 |-WARN in ch.qos.logback.classic.AsyncAppender[ASYNC] - Ignoring additional appender named [CONSOLE]
16:05:50,189 |-INFO in ch.qos.logback.classic.AsyncAppender[ASYNC] - Setting discardingThreshold to 200
16:05:50,189 |-INFO in ch.qos.logback.classic.joran.action.LoggerAction - Setting level of logger [me.superblaubeere27] to DEBUG
16:05:50,190 |-INFO in ch.qos.logback.classic.joran.action.RootLoggerAction - Setting level of ROOT logger to DEBUG
16:05:50,190 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [ASYNC] to Logger[ROOT]
16:05:50,190 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - End of configuration.
16:05:50,190 |-INFO in ch.qos.logback.classic.joran.JoranConfigurator@2ac273d3 - Registering current configuration as safe fallback point

java.lang.IllegalArgumentException: Unsupported class file major version 66
	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:199)
	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:180)
	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:166)
	at me.superblaubeere27.jobf.JObfImpl.processJar(JObfImpl.java:421)
	at me.superblaubeere27.jobf.ui.GUI.lambda$startObfuscator$15(GUI.java:402)
	at java.base/java.lang.Thread.run(Thread.java:1570)

**Comment by KnoxTheDev** [comment]
@Beninwende Recompile your code with Java 21.

**Comment by Zcraft3793** [comment]
Download the latest version of ASM from [this link](https://asm.ow2.io/) and replace the outdated ASM in the JAR file
