### ISSUE TITLE
Obfuscator breaks jars without processors (Bad ASM?)

### ISSUE THREAD

**Issue by spongebobe** [superblaubeere27/obfuscator#29]
# Bug Report
I was testing the obfuscator with some jars and it was breaking some of the classes without any processors on whatsoever. The jars would not play nice with other obfuscators or decompilers (because they were broke)

I not only disabled all processors, but I completely removed them from the code, I applied function isObfuscatorEnabledForClass(node) {
    return false;
}
and everything, and it is still breaking jars.

### How to reproduce the behaviour
I found that kilo best represents this bug, so here is a compiled version for you to test out.
Jar: 
https://4lpha.one/dl/1CTswpE6WzAUkOheBKijWKTPK8PvRJmWk
Config:
https://pastebin.com/aWbqNRxQ

So you obf the jar and it should still work because nothing should've been changed, but this isn't the case. Try to obfuscate on top of Jobf with something like Radon or another obfuscator and you'll get multiple errors about failing to read/write classes; errors that weren't there on the unobf version. This only happens when jars are obfed with jobf, and since no processors are applied, I would assume it's a bug in your reading/writing part of the obfuscator. Please fix soon.

### Classes you can compare pre and post
On radon it told me
WARNING: Could not load net/minecraft/command/common/CommandReplaceItem.class as a class
WARNING: Could not load jaco/mp3/player/MP3Player$1.class as a class

**Comment by superblaubeere27** [comment]
What is the error message the JVM gives you?

**Comment by spongebobe** [comment]
###CommandReplaceItem causes
java.lang.IllegalArgumentException
	at org.objectweb.asm.ClassReader.readConst(ClassReader.java:3600)
	at org.objectweb.asm.ClassReader.readCode(ClassReader.java:2187)
	at org.objectweb.asm.ClassReader.readMethod(ClassReader.java:1275)
	at org.objectweb.asm.ClassReader.accept(ClassReader.java:679)
	at org.objectweb.asm.ClassReader.accept(ClassReader.java:391)
	at me.itzsomebody.radon.Radon.loadInput(Radon.java:200)
	at me.itzsomebody.radon.Radon.partyTime(Radon.java:79)
	at me.itzsomebody.radon.CLI.startTheParty(CLI.java:78)
	at me.itzsomebody.radon.CLI.<init>(CLI.java:47)
	at me.itzsomebody.radon.Main.main(Main.java:57)
###MP3Player$1 causes
java.lang.ArrayIndexOutOfBoundsException: 4394
	at org.objectweb.asm.ClassReader.readConst(ClassReader.java:3571)
	at org.objectweb.asm.ClassReader.readCode(ClassReader.java:2187)
	at org.objectweb.asm.ClassReader.readMethod(ClassReader.java:1275)
	at org.objectweb.asm.ClassReader.accept(ClassReader.java:679)
	at org.objectweb.asm.ClassReader.accept(ClassReader.java:391)
	at me.itzsomebody.radon.Radon.loadInput(Radon.java:200)
	at me.itzsomebody.radon.Radon.partyTime(Radon.java:79)
	at me.itzsomebody.radon.CLI.startTheParty(CLI.java:78)
	at me.itzsomebody.radon.CLI.<init>(CLI.java:47)
	at me.itzsomebody.radon.Main.main(Main.java:57)

**Comment by superblaubeere27** [comment]
uh can you please tell me what happens when you run the jar as intended?

**Comment by spongebobe** [comment]
it doesn't work in some cases. the point is, it needs to be compatible with other obfuscators. it isn't your transformers breaking the jar, it is the fundamental reading and writing of your obfuscator.

**Comment by superblaubeere27** [comment]
The reading and writing is done by ASM. I don't write the classes myself :/

**Comment by spongebobe** [comment]
I'm saying your ASM is not the same as something like Radon. Your ClassReader and ClassWriter have different parameters like SKIP_CODE SKIP_FRAMES etc. Please just look into how you and other obfuscators read/write the jar because you're the only obfuscator that messes it up.

**Comment by superblaubeere27** [comment]
@spongebobe the Flags passed to the ClassReader and ClassWriter doesn't affect the validity of the class files.

**Comment by superblaubeere27** [comment]
I wasn't able to reproduce the behaviour. If another program can't deal with it it is probably caused by an older version of ASM.
