### ISSUE TITLE
Cannot Execute Program

### ISSUE THREAD

**Issue by AggroMC** [superblaubeere27/obfuscator#35]
I wanted to start the obfuscator, then this happened: (I did java -jar obfuscator.jar)

ERROR: Missing required option(s) [jarIn] (Tip: try --help and even if you specified a config you have to specify an input and output jar)
joptsimple.MissingRequiredOptionsException: Missing required option(s) [jarIn]
	at joptsimple.OptionParser.ensureRequiredOptions(OptionParser.java:426)
	at joptsimple.OptionParser.parse(OptionParser.java:400)
	at me.superblaubeere27.jobf.JObf.main(JObf.java:117)
Starting in GUI Mode
No protocol specified
Exception in thread "main" java.lang.NoClassDefFoundError: Could not initialize class sun.awt.X11GraphicsEnvironment
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at java.awt.GraphicsEnvironment.createGE(GraphicsEnvironment.java:103)
	at java.awt.GraphicsEnvironment.getLocalGraphicsEnvironment(GraphicsEnvironment.java:82)
	at java.awt.Window.initGC(Window.java:475)
	at java.awt.Window.init(Window.java:495)
	at java.awt.Window.<init>(Window.java:537)
	at java.awt.Frame.<init>(Frame.java:420)
	at java.awt.Frame.<init>(Frame.java:385)
	at javax.swing.JFrame.<init>(JFrame.java:189)
	at me.superblaubeere27.jobf.ui.GUI.<init>(GUI.java:80)
	at me.superblaubeere27.jobf.JObf.main(JObf.java:273)

What should i do now?

**Comment by superblaubeere27** [comment]
Which Java Version? Which OS?

**Comment by AggroMC** [comment]
openjdk version "1.8.0_212"
OpenJDK Runtime Environment (build 1.8.0_212-8u212-b01-1~deb9u1-b01)
OpenJDK 64-Bit Server VM (build 25.212-b01, mixed mode)

and the OS is Debian 9

**Comment by superblaubeere27** [comment]
Ok this might be a bug the the new UI Theme. Can you try an older version?

**Comment by AggroMC** [comment]
Yes I can try it but Can you give an 'Only Command Line' build? That's enough for me

**Comment by superblaubeere27** [comment]
@AggroMC Start the obfuscator with the argument `-Djava.awt.headless=true`, e.g. `java -Djava.awt.headless=true -jar obfuscator.jar`

**Comment by AggroMC** [comment]
Ok I will try it. Do you speak German btw?

**Comment by AggroMC** [comment]
Wenn ich es mit der obigen Methode versuche, bekomme ich diesen Fehler:

"root@laptop-steve:/home/steve/Schreibtisch/obf# java -Djava.awt.headless=true -jar obfuscator.jar --mode 1 --package --packagerMainClass de.SteveaggroYT.ForceOP.Main.main --jarIn ForceOP.jar --jarOut ForceOP-Com.jar
ERROR: mode is not a recognized option (Tip: try --help and even if you specified a config you have to specify an input and output jar)
joptsimple.UnrecognizedOptionException: mode is not a recognized option
	at joptsimple.OptionException.unrecognizedOption(OptionException.java:108)
	at joptsimple.OptionParser.handleLongOptionToken(OptionParser.java:510)
	at joptsimple.OptionParserState$2.handleArgument(OptionParserState.java:56)
	at joptsimple.OptionParser.parse(OptionParser.java:396)
	at me.superblaubeere27.jobf.JObf.main(JObf.java:117)
root@laptop-steve:/home/steve/Schreibtisch/obf# "

Wenn ich --mode 1 weglasse kommt:

"root@laptop-steve:/home/steve/Schreibtisch/obf# java -Djava.awt.headless=true -jar obfuscator.jar --package --packagerMainClass de.SteveaggroYT.ForceOP.Main.main --jarIn ForceOP.jar --jarOut ForceOP-Com.jar
ERROR: package is not a recognized option (Tip: try --help and even if you specified a config you have to specify an input and output jar)
joptsimple.UnrecognizedOptionException: package is not a recognized option
	at joptsimple.OptionException.unrecognizedOption(OptionException.java:108)
	at joptsimple.OptionParser.handleLongOptionToken(OptionParser.java:510)
	at joptsimple.OptionParserState$2.handleArgument(OptionParserState.java:56)
	at joptsimple.OptionParser.parse(OptionParser.java:396)
	at me.superblaubeere27.jobf.JObf.main(JObf.java:117)
root@laptop-steve:/home/steve/Schreibtisch/obf#"

Was soll ich tun?

**Comment by AggroMC** [comment]
And thats Happening when i try to start Obfuscator 1.8 to 1.9.3:

root@laptop-steve:/home/steve/Downloads# java -jar obfuscator-1.9.jar
ERROR: Missing required option(s) [jarIn] (Tip: try --help and even if you specified a config you have to specify an input and output jar)
joptsimple.MissingRequiredOptionsException: Missing required option(s) [jarIn]
	at joptsimple.OptionParser.ensureRequiredOptions(OptionParser.java:426)
	at joptsimple.OptionParser.parse(OptionParser.java:400)
	at me.superblaubeere27.jobf.JObf.main(JObf.java:117)
Starting in GUI Mode
No protocol specified
Exception in thread "main" java.lang.NoClassDefFoundError: Could not initialize class sun.awt.X11GraphicsEnvironment
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at java.awt.GraphicsEnvironment.createGE(GraphicsEnvironment.java:103)
	at java.awt.GraphicsEnvironment.getLocalGraphicsEnvironment(GraphicsEnvironment.java:82)
	at java.awt.Window.initGC(Window.java:475)
	at java.awt.Window.init(Window.java:495)
	at java.awt.Window.<init>(Window.java:537)
	at java.awt.Frame.<init>(Frame.java:420)
	at java.awt.Frame.<init>(Frame.java:385)
	at javax.swing.JFrame.<init>(JFrame.java:189)
	at me.superblaubeere27.jobf.ui.GUI.<init>(GUI.java:78)
	at me.superblaubeere27.jobf.JObf.main(JObf.java:273)
root@laptop-steve:/home/steve/Downloads# java -jar obfuscator-1.9.1.jar
ERROR: Missing required option(s) [jarIn] (Tip: try --help and even if you specified a config you have to specify an input and output jar)
joptsimple.MissingRequiredOptionsException: Missing required option(s) [jarIn]
	at joptsimple.OptionParser.ensureRequiredOptions(OptionParser.java:426)
	at joptsimple.OptionParser.parse(OptionParser.java:400)
	at me.superblaubeere27.jobf.JObf.main(JObf.java:117)
Starting in GUI Mode
No protocol specified
Exception in thread "main" java.lang.NoClassDefFoundError: Could not initialize class sun.awt.X11GraphicsEnvironment
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at java.awt.GraphicsEnvironment.createGE(GraphicsEnvironment.java:103)
	at java.awt.GraphicsEnvironment.getLocalGraphicsEnvironment(GraphicsEnvironment.java:82)
	at java.awt.Window.initGC(Window.java:475)
	at java.awt.Window.init(Window.java:495)
	at java.awt.Window.<init>(Window.java:537)
	at java.awt.Frame.<init>(Frame.java:420)
	at java.awt.Frame.<init>(Frame.java:385)
	at javax.swing.JFrame.<init>(JFrame.java:189)
	at me.superblaubeere27.jobf.ui.GUI.<init>(GUI.java:78)
	at me.superblaubeere27.jobf.JObf.main(JObf.java:273)
root@laptop-steve:/home/steve/Downloads# java -jar obfuscator-1.9.2.jar
ERROR: Missing required option(s) [jarIn] (Tip: try --help and even if you specified a config you have to specify an input and output jar)
joptsimple.MissingRequiredOptionsException: Missing required option(s) [jarIn]
	at joptsimple.OptionParser.ensureRequiredOptions(OptionParser.java:426)
	at joptsimple.OptionParser.parse(OptionParser.java:400)
	at me.superblaubeere27.jobf.JObf.main(JObf.java:117)
Starting in GUI Mode
No protocol specified
Exception in thread "main" java.lang.NoClassDefFoundError: Could not initialize class sun.awt.X11GraphicsEnvironment
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at java.awt.GraphicsEnvironment.createGE(GraphicsEnvironment.java:103)
	at java.awt.GraphicsEnvironment.getLocalGraphicsEnvironment(GraphicsEnvironment.java:82)
	at java.awt.Window.initGC(Window.java:475)
	at java.awt.Window.init(Window.java:495)
	at java.awt.Window.<init>(Window.java:537)
	at java.awt.Frame.<init>(Frame.java:420)
	at java.awt.Frame.<init>(Frame.java:385)
	at javax.swing.JFrame.<init>(JFrame.java:189)
	at me.superblaubeere27.jobf.ui.GUI.<init>(GUI.java:80)
	at me.superblaubeere27.jobf.JObf.main(JObf.java:273)
root@laptop-steve:/home/steve/Downloads# java -jar obfuscator-1.9.3.jar
ERROR: Missing required option(s) [jarIn] (Tip: try --help and even if you specified a config you have to specify an input and output jar)
joptsimple.MissingRequiredOptionsException: Missing required option(s) [jarIn]
	at joptsimple.OptionParser.ensureRequiredOptions(OptionParser.java:426)
	at joptsimple.OptionParser.parse(OptionParser.java:400)
	at me.superblaubeere27.jobf.JObf.main(JObf.java:117)
Starting in GUI Mode
No protocol specified
Exception in thread "main" java.lang.NoClassDefFoundError: Could not initialize class sun.awt.X11GraphicsEnvironment
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at java.awt.GraphicsEnvironment.createGE(GraphicsEnvironment.java:103)
	at java.awt.GraphicsEnvironment.getLocalGraphicsEnvironment(GraphicsEnvironment.java:82)
	at java.awt.Window.initGC(Window.java:475)
	at java.awt.Window.init(Window.java:495)
	at java.awt.Window.<init>(Window.java:537)
	at java.awt.Frame.<init>(Frame.java:420)
	at java.awt.Frame.<init>(Frame.java:385)
	at javax.swing.JFrame.<init>(JFrame.java:189)
	at me.superblaubeere27.jobf.ui.GUI.<init>(GUI.java:80)
	at me.superblaubeere27.jobf.JObf.main(JObf.java:273)
root@laptop-steve:/home/steve/Downloads# java -jar obfuscator-1.71.jar
No protocol specified
Exception in thread "main" java.awt.AWTError: Can't connect to X11 window server using ':0.0' as the value of the DISPLAY variable.
	at sun.awt.X11GraphicsEnvironment.initDisplay(Native Method)
	at sun.awt.X11GraphicsEnvironment.access$200(X11GraphicsEnvironment.java:65)
	at sun.awt.X11GraphicsEnvironment$1.run(X11GraphicsEnvironment.java:115)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.awt.X11GraphicsEnvironment.<clinit>(X11GraphicsEnvironment.java:74)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at java.awt.GraphicsEnvironment.createGE(GraphicsEnvironment.java:103)
	at java.awt.GraphicsEnvironment.getLocalGraphicsEnvironment(GraphicsEnvironment.java:82)
	at sun.awt.X11.XToolkit.<clinit>(XToolkit.java:132)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at java.awt.Toolkit$2.run(Toolkit.java:860)
	at java.awt.Toolkit$2.run(Toolkit.java:855)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.awt.Toolkit.getDefaultToolkit(Toolkit.java:854)
	at javax.swing.UIManager.getSystemLookAndFeelClassName(UIManager.java:611)
	at me.superblaubeere27.jobf.JObf.main(JObf.java:158)
root@laptop-steve:/home/steve/Downloads# java -jar obfuscator-1.8.jar
No protocol specified
Exception in thread "main" java.awt.AWTError: Can't connect to X11 window server using ':0.0' as the value of the DISPLAY variable.
	at sun.awt.X11GraphicsEnvironment.initDisplay(Native Method)
	at sun.awt.X11GraphicsEnvironment.access$200(X11GraphicsEnvironment.java:65)
	at sun.awt.X11GraphicsEnvironment$1.run(X11GraphicsEnvironment.java:115)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.awt.X11GraphicsEnvironment.<clinit>(X11GraphicsEnvironment.java:74)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at java.awt.GraphicsEnvironment.createGE(GraphicsEnvironment.java:103)
	at java.awt.GraphicsEnvironment.getLocalGraphicsEnvironment(GraphicsEnvironment.java:82)
	at sun.awt.X11.XToolkit.<clinit>(XToolkit.java:132)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at java.awt.Toolkit$2.run(Toolkit.java:860)
	at java.awt.Toolkit$2.run(Toolkit.java:855)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.awt.Toolkit.getDefaultToolkit(Toolkit.java:854)
	at javax.swing.UIManager.getSystemLookAndFeelClassName(UIManager.java:611)
	at me.superblaubeere27.jobf.JObf.main(JObf.java:158)
root@laptop-steve:/home/steve/Downloads#

**Comment by superblaubeere27** [comment]
@AggroMC Die Dokumentation in der README.md ist outdated... Es gibt jetzt nur noch `.config`. Ich update die mit dem nächsten Release mit ^^

**Comment by superblaubeere27** [comment]
Und das Theme wird Optional

**Comment by superblaubeere27** [comment]
I opened a new issue #38

**Comment by superblaubeere27** [comment]
Fixed in 588c6c9
