### ISSUE TITLE
Is not working with HTTPClient and JSON libraries

### ISSUE THREAD

**Issue by marcoVera** [superblaubeere27/obfuscator#39]
# Bug Report
### Expected Behaviour
Tell us what you wanted to do. If you think that everyone knows, what you expected (for example, if the program just crashed), you can skip this section
### Actual Behaviour
Tell us what happened. If there is an Exception please attach it.
### How to reproduce the behaviour
Tell us how to reproduce the wrong behaviour of the program. If it's an error which has to do this the obfuscation please **always** attach the configuration. 
(To get the config open the obfuscator in GUI-Mode, goto `Config`, enable `PrettyPrint` and press `Build`)
### Possible fix
If you have no idea then you can just skip this section ^^

**Comment by superblaubeere27** [comment]
I'll try to reproduce this issue... Btw, I edited your comment (Just changed the code formatting)

**Comment by superblaubeere27** [comment]
Uhm, can you please provide your configuration?

**Comment by AuligPromotions** [comment]
Same happening for me on 1.9.3 using default config. What feature could be causing this?

**Comment by AuligPromotions** [comment]
I think I fixed it by disabling Bad Concat.

**Comment by superblaubeere27** [comment]
@AuligPromotions Interesting...

**Comment by marcoVera** [comment]
"I think I fixed it by disabling Bad Concat"
I removed all options and just leaves without anything and still was not working, something with http and json functionality is not working well

**Comment by superblaubeere27** [comment]
@marcoVera java version?

**Comment by marcoVera** [comment]
Java 8

**Comment by superblaubeere27** [comment]
@marcoVera I will introduce some new unit test to tests if the obfuscator has any bugs.

**Comment by JH3Y50N** [comment]
`23.02 19:53:09 [Server] WARN java.security.InvalidKeyException: Illegal key size or default parameters
23.02 19:53:09 [Server] WARN at javax.crypto.Cipher.checkCryptoPerm(Cipher.java:1026)
23.02 19:53:09 [Server] WARN at javax.crypto.Cipher.implInit(Cipher.java:801)
23.02 19:53:09 [Server] WARN at javax.crypto.Cipher.chooseProvider(Cipher.java:864)
23.02 19:53:09 [Server] WARN at javax.crypto.Cipher.init(Cipher.java:1249)
23.02 19:53:09 [Server] WARN at javax.crypto.Cipher.init(Cipher.java:1186)`

**Comment by superblaubeere27** [comment]
@JH3Y50N Did you enable `AES`?

**Comment by JH3Y50N** [comment]
> @JH3Y50N Did you enable `AES`?

yes

**Comment by superblaubeere27** [comment]
@JH3Y50N `AES` is marked as `Proceed with caution` since it can easily break your code. Just turn it of and it will work ;D

**Comment by SkillC0de** [comment]
I have the same problem, its not working with http/json.
