### ISSUE TITLE
I can't use the gui!

### ISSUE THREAD

**Issue by liaic** [superblaubeere27/obfuscator#48]
ERROR: Missing required option(s) [jarIn] (Tip: try --help and even if you specified a config you have to specify an input and output jar)
joptsimple.MissingRequiredOptionsException: Missing required option(s) [jarIn]
        at joptsimple.OptionParser.ensureRequiredOptions(OptionParser.java:426)
        at joptsimple.OptionParser.parse(OptionParser.java:400)
        at me.superblaubeere27.jobf.JObf.main(JObf.java:117)
Starting in GUI Mode
Exception in thread "main" java.lang.NullPointerException
        at java.io.FilterInputStream.read(Unknown Source)
        at sun.nio.cs.StreamDecoder.readBytes(Unknown Source)
        at sun.nio.cs.StreamDecoder.implRead(Unknown Source)
        at sun.nio.cs.StreamDecoder.read(Unknown Source)
        at java.io.InputStreamReader.read(Unknown Source)
        at java.io.BufferedReader.fill(Unknown Source)
        at java.io.BufferedReader.readLine(Unknown Source)
        at java.io.BufferedReader.readLine(Unknown Source)
        at me.superblaubeere27.jobf.utils.Templates.getResourceFiles(Templates.java:41)
        at me.superblaubeere27.jobf.utils.Templates.loadTemplates(Templates.java:25)
        at me.superblaubeere27.jobf.JObf.main(JObf.java:269)
        Suppressed: java.lang.NullPointerException
                at java.io.FilterInputStream.close(Unknown Source)
                at sun.net.www.protocol.jar.JarURLConnection$JarURLInputStream.close(Unknown Source)
                at sun.nio.cs.StreamDecoder.implClose(Unknown Source)
                at sun.nio.cs.StreamDecoder.close(Unknown Source)
                at java.io.InputStreamReader.close(Unknown Source)
                at java.io.BufferedReader.close(Unknown Source)
                at me.superblaubeere27.jobf.utils.Templates.getResourceFiles(Templates.java:44)
                ... 2 more
        Suppressed: java.lang.NullPointerException
                at java.io.FilterInputStream.close(Unknown Source)
                at sun.net.www.protocol.jar.JarURLConnection$JarURLInputStream.close(Unknown Source)
                at me.superblaubeere27.jobf.utils.Templates.getResourceFiles(Templates.java:44)
                ... 2 more

**Comment by superblaubeere27** [comment]
Which JAR are you using?

**Comment by liaic** [comment]
The obfuscator-1.9.3.jar

**Comment by liaic** [comment]
using cmd java -jar obfuscator-1.9.3.jar start

**Comment by superblaubeere27** [comment]
which java version and which OS?

**Comment by cookiedragon234** [comment]
Sounds like your running the jar using `java -jar obfuscator-1.9.3.jar start`. The correct format is `java -jar obfuscator-1.9.3.jar --jarIn helloWorld.jar --jarOut helloWorld-obf.jar` as specified in the readme (https://github.com/superblaubeere27/obfuscator/blob/master/README.md#examples). Please let me know if this fixes your issue so that I can close it.

**Comment by liaic** [comment]
it's my  javaversion problem, seems the window cann't been showed in jre7

**Comment by superblaubeere27** [comment]
@liaic Yes. The obfuscator requires JRE 8. If you run it with this it should run fine

**Comment by cookiedragon234** [comment]
Seems to be solved, closing
