### ISSUE TITLE
Compression Level Store support for jar creation

### ISSUE THREAD

**Issue by MrABKhan** [superblaubeere27/obfuscator#59]
# Feature Request
- Describe the feature
- Tell us why should add this feature

The Obfuscated Jars created are compressed to some point thus Spring Boot jars don't work with compressed "libs" folder.

For Now I'm bypassing the issue but replacing the "libs" folder in the obfuscated jar manually through winRAR with compression level as "STORE"

It would be great if you can add the option to create Jars with "STORE" or No compression so that Spring Boot jars can work again.

**Comment by MrABKhan** [comment]
```

Caused by: java.io.IOException: Unable to open nested jar file 'BOOT-INF/lib/logback-classic-1.2.3.jar'                                                                                                                                                                                 at org.springframework.boot.loader.jar.JarFile.getNestedJarFile(JarFile.java:256)                                                                                                                                                                                               at org.springframework.boot.loader.jar.JarFile.getNestedJarFile(JarFile.java:241)                                                                                                                                                                                               at org.springframework.boot.loader.archive.JarFileArchive.getNestedArchive(JarFileArchive.java:103)                                                                                                                                                                             ... 4 more                                                                                                                                                                                                                                                              Caused by: java.lang.IllegalStateException: Unable to open nested entry 'BOOT-INF/lib/logback-classic-1.2.3.jar'. It has been compressed and nested jar files must be stored without compression. Please check the mechanism used to create your executable jar file                    at org.springframework.boot.loader.jar.JarFile.createJarFileFromFileEntry(JarFile.java:284)                                                                                                                                                                                     at org.springframework.boot.loader.jar.JarFile.createJarFileFromEntry(JarFile.java:264)                                                                                                                                                                                         at org.springframework.boot.loader.jar.JarFile.getNestedJarFile(JarFile.java:252)                                                                                                                                                                                               ... 6 more
--



```

**Comment by superblaubeere27** [comment]
I would have never thought about any program having a problem with DEFLATE zips. But I can fix this

**Comment by superblaubeere27** [comment]
I added it in 7b8363a. Here is the latest build. Please tell me if it works https://jitpack.io/com/github/superblaubeere27/obfuscator/obfuscator-core/7b8363a9b4/obfuscator-core-7b8363a9b4.jar

**Comment by MrABKhan** [comment]
Thank You It works now!

but I think scripts tab is not working, as I added a script to exclude some packages from all obfuscation and now it doesn't work as it obfuscates everything

**Comment by MrABKhan** [comment]
Thank You It works now :D


Spring Boot Jars are now supported! 


edit : deleted previous comment due to bug in my own script. Cheers 🥇

**Comment by jamnikr** [comment]
I downloaded the version with this fix and the problem still occurs.
Caused by: java.lang.IllegalStateException: Unable to open nested entry 'BOOT-INF/lib/log4j-api-2.12.1.jar'. It has been compressed and nested jar files must be stored without compression. Please check the mechanism used to create your executable jar file
	at org.springframework.boot.loader.jar.JarFile.createJarFileFromFileEntry(Unknown Source)
	at org.springframework.boot.loader.jar.JarFile.createJarFileFromEntry(Unknown Source)

**Comment by MrABKhan** [comment]
@jamnikr have you checked the button on the UI for Spring Boot compression?

**Comment by jamnikr** [comment]
Yes, it works perfect :) I didn't notice this option.

**Comment by halower** [comment]
@jamnikr @MrABKhan how to add  this option?

**Comment by MrABKhan** [comment]
@halower there is option in the UI to enable this.

**Comment by halower** [comment]
sorry， i can't understand this option,  project is based on springboot , when i set Optimizer.enabled= false in config,   when i run the project that throw an exception `Exception in thread "main" java.lang.IllegalStateException: Failed to get nested archive for entry BOOT-INF/lib/commons-math3-3.6.1.jar`，I want you to write a command example for springboot， thank you .

**Comment by kkocel** [comment]
@superblaubeere27 is this option available through json configuration as well?

**Comment by heykb** [comment]
I downloaded the version with this fix . but get
+----------------------------------------------------------------------------------------------------+
ERROR: Failed to load names:
java.lang.RuntimeException: Failed to load names:
        at me.superblaubeere27.jobf.utils.NameUtils.applySettings(NameUtils.java:200)
        at me.superblaubeere27.jobf.JObfImpl.processJar(JObfImpl.java:286)
        at me.superblaubeere27.jobf.JObf.runObfuscator(JObf.java:287)
        at me.superblaubeere27.jobf.JObf.main(JObf.java:156)
Caused by: java.io.FileNotFoundException:
        at java.io.FileInputStream.open0(Native Method)
        at java.io.FileInputStream.open(FileInputStream.java:195)
        at java.io.FileInputStream.<init>(FileInputStream.java:138)
        at com.google.common.io.Files$FileByteSource.openStream(Files.java:129)
        at com.google.common.io.Files$FileByteSource.openStream(Files.java:119)
        at com.google.common.io.ByteSource$AsCharSource.openStream(ByteSource.java:458)
        at com.google.common.io.CharSource.readLines(CharSource.java:359)
        at com.google.common.io.Files.readLines(Files.java:525)
        at me.superblaubeere27.jobf.utils.NameUtils.applySettings(NameUtils.java:196)
        ... 3 more
