### ISSUE TITLE
Obf. ERROR

### ISSUE THREAD

**Issue by DevTimBudarick** [superblaubeere27/obfuscator#6]
java.lang.IllegalArgumentException
        at org.objectweb.asm.ClassReader.<init>(ClassReader.java:185)
        at org.objectweb.asm.ClassReader.<init>(ClassReader.java:168)
        at me.superblaubeere27.jobf.JObfImpl.processJar(JObfImpl.java:406)
        at me.superblaubeere27.jobf.JObfImpl.processConsole(JObfImpl.java:98)
        at me.superblaubeere27.jobf.JObf.main(JObf.java:141)
Processed Application.jar

**Comment by superblaubeere27** [comment]
Entschuldigung, dass du so lange warten musstest.
Kannst du es mal mit der neusten Version probieren und wenn es damit nicht geht, mir deine config, in jar und out jar zu senden?

**Comment by Zaxar163** [comment]
He used it after Radon or the same.

**Comment by superblaubeere27** [comment]
@Zaxar163 If it doesn't work after Radon, it is Radon's problem not mine :/
