### ISSUE TITLE
it does not work on springboot,after obfuscation,it can not run

### ISSUE THREAD

**Issue by 1101302428** [superblaubeere27/obfuscator#61]
# Bug Report
### Expected Behaviour
it does not work on springboot,after obfuscation,it can not run,and it show "Exception in thread "main" java.lang.IllegalStateException: Failed to get nested archive for entry BOOT-INF/lib/spring-jcl-5.1.9.RELEASE.jar" and "Caused by: java.lang.IllegalStateException: Unable to open nested entry 'BOOT-INF/lib/spring-jcl-5.1.9.RELEASE.jar'. It has been compressed and nested jar files must be stored without compression. Please check the mechanism used to create your executable jar file"
### Actual Behaviour
Exception in thread "main" java.lang.IllegalStateException: Failed to get nested archive for entry BOOT-INF/lib/spring-jcl-5.1.9.RELEASE.jar
        at org.springframework.boot.loader.archive.JarFileArchive.getNestedArchive(Unknown Source)
        at org.springframework.boot.loader.archive.JarFileArchive.getNestedArchives(Unknown Source)
        at org.springframework.boot.loader.ExecutableArchiveLauncher.getClassPathArchives(Unknown Source)
        at org.springframework.boot.loader.Launcher.launch(Unknown Source)
        at org.springframework.boot.loader.JarLauncher.main(Unknown Source)
Caused by: java.io.IOException: Unable to open nested jar file 'BOOT-INF/lib/spring-jcl-5.1.9.RELEASE.jar'
        at org.springframework.boot.loader.jar.JarFile.getNestedJarFile(Unknown Source)
        at org.springframework.boot.loader.jar.JarFile.getNestedJarFile(Unknown Source)
        ... 5 more
Caused by: java.lang.IllegalStateException: Unable to open nested entry 'BOOT-INF/lib/spring-jcl-5.1.9.RELEASE.jar'. It has been compressed and nested jar files must be stored without compression. Please check the mechanism used to create your executable jar file
        at org.springframework.boot.loader.jar.JarFile.createJarFileFromFileEntry(Unknown Source)
        at org.springframework.boot.loader.jar.JarFile.createJarFileFromEntry(Unknown Source)
        ... 7 more
### How to reproduce the behaviour
Tell us how to reproduce the wrong behaviour of the program. If it's an error which has to do this the obfuscation please **always** attach the configuration. 
(To get the config open the obfuscator in GUI-Mode, goto `Config`, enable `PrettyPrint` and press `Build`)
### Possible fix
If you have no idea then you can just skip this section ^^

**Comment by superblaubeere27** [comment]
See #59
