### ISSUE TITLE
How to use Packager

### ISSUE THREAD

**Issue by wyw900807** [superblaubeere27/obfuscator#67]
If I enable Packager and use MainClass from the JAR manifest, when running the jar, the console shows :
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at IIIlllllIIlIl.main(Unknown Source)
Caused by: java.lang.IllegalStateException: java.lang.NullPointerException
	at org.springframework.boot.loader.ExecutableArchiveLauncher.<init>(Unknown Source)
	at org.springframework.boot.loader.JarLauncher.<init>(Unknown Source)
	at org.springframework.boot.loader.JarLauncher.main(Unknown Source)
	... 5 more
Caused by: java.lang.NullPointerException
	at org.springframework.boot.loader.Launcher.createArchive(Unknown Source)
	... 8 more

**Comment by cookiedragon234** [comment]
Packer doesn’t work alongside frameworks that are based on reflection, like spring boot.
