### ISSUE TITLE
java.lang.ArraylndexOutOfBoundsException: 29

### ISSUE THREAD

**Issue by chirstwy** [superblaubeere27/obfuscator#83]
When running confusion(Loading classpath...), this exception was thrown, how to solve it?

**Comment by cookiedragon234** [comment]
Please post the entire stacktrace

**Comment by chirstwy** [comment]
> Please post the entire stacktrace
Loading classpath...
java.lang.ArrayIndexOutOfBoundsException: 29
        at org.objectweb.asm.ClassReader.readUtf(ClassReader.java:3425)
        at org.objectweb.asm.ClassReader.readUTF8(ClassReader.java:3412)
        at org.objectweb.asm.ClassReader.readStringish(ClassReader.java:3481)
        at org.objectweb.asm.ClassReader.readModule(ClassReader.java:3509)
        at org.objectweb.asm.ClassReader.readModuleAttributes(ClassReader.java:711)
        at org.objectweb.asm.ClassReader.accept(ClassReader.java:535)
        at org.objectweb.asm.ClassReader.accept(ClassReader.java:391)
        at me.superblaubeere27.jobf.JObfImpl.loadClasspathFile(JObfImpl.java:134)
        at me.superblaubeere27.jobf.JObfImpl.lambda$loadClasspath$1(JObfImpl.java:153)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
        at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
        at java.util.Iterator.forEachRemaining(Iterator.java:116)
        at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
        at me.superblaubeere27.jobf.JObfImpl.loadClasspath(JObfImpl.java:151)
        at me.superblaubeere27.jobf.JObfImpl.processJar(JObfImpl.java:234)
        at me.superblaubeere27.jobf.ui.GUI.lambda$startObfuscator$13(GUI.java:316)
        at java.lang.Thread.run(Thread.java:748)

**Comment by chirstwy** [comment]
> Please post the entire stacktrace

This exception occurs when the program adds dependent jars. Is it possible to obfuscate without adding dependent packages?

**Comment by cookiedragon234** [comment]
It sounds like one of your libraries has invalid classes, we should have better handling for this when loading librariws

**Comment by chirstwy** [comment]
Is there no way to solve this exception in your obfuscated program, only from my dependent libraries?

**Comment by chirstwy** [comment]
> It sounds like one of your libraries has invalid classes, we should have better handling for this when loading libraries

Because I use dependency libraries directly, I don't know how to find invalid classes from the dependency libraries?
