### ISSUE TITLE
MethodTooLargeException

### ISSUE THREAD

**Issue by kanekireal** [superblaubeere27/obfuscator#86]
org.objectweb.asm.MethodTooLargeException: Method too large: org/apache/commons/codec/digest/PureJavaCrc32C.lIlllllllIIlI ()V
	at org.objectweb.asm.MethodWriter.computeMethodInfoSize(MethodWriter.java:2089)
	at org.objectweb.asm.ClassWriter.toByteArray(ClassWriter.java:458)
	at me.superblaubeere27.jobf.JObfImpl.lambda$processJar$6(JObfImpl.java:406)
	at java.lang.Thread.run(Thread.java:748)
org.objectweb.asm.MethodTooLargeException: Method too large: org/apache/commons/codec/digest/PureJavaCrc32.llIIIIIlIllIlI ()V
	at org.objectweb.asm.MethodWriter.computeMethodInfoSize(MethodWriter.java:2089)
	at org.objectweb.asm.ClassWriter.toByteArray(ClassWriter.java:458)
	at me.superblaubeere27.jobf.JObfImpl.lambda$processJar$6(JObfImpl.java:406)
	at java.lang.Thread.run(Thread.java:748)

# Bug Report
### Expected Behaviour
Tell us what you wanted to do. If you think that everyone knows, what you expected (for example, if the program just crashed), you can skip this section
### Actual Behaviour
Tell us what happened. If there is an Exception please attach it.
### How to reproduce the behaviour
Tell us how to reproduce the wrong behaviour of the program. If it's an error which has to do this the obfuscation please **always** attach the configuration. 
(To get the config open the obfuscator in GUI-Mode, goto `Config`, enable `PrettyPrint` and press `Build`)
### Possible fix
If you have no idea then you can just skip this section ^^

**Comment by cookiedragon234** [comment]
You must manually exclude these methods from being obfuscated, sorry

**Comment by kaptanbu** [comment]
I got same error. In configuration, If i disabled NumberObfuscation, there is no error. I use CLI. My configuration in below,

`"Crasher": {
    "Enabled": false
  },
  "InvokeDynamic": {
    "Enabled": false
  },
  "HWIDPRotection": {
    "Enabled": false,
    "HWID": "C2EDFD50341322AFBABFF48F211"
  },
  "Optimizer": {
    "Enabled": false,
    "Replace String.equals()": false,
    "Replace String.equalsIgnoreCase()": false,
    "Optimize static string calls": false
  },
  "LineNumberRemover": {
    "Enabled": true,
    "Rename local variables": true,
    "Remove Line Numbers": true,
    "Remove Debug Names": true,
    "Add Local Variables": true,
    "New SourceFile Name": ""
  },
  "StringEncryption": {
    "Enabled": true,
    "HideStrings": true,
    "AES": false
  },
  "NumberObfuscation": {
    "Enabled": false,
    "Extract to Array": true,
    "Obfuscate Zero": true,
    "Shift": false,
    "And": false,
    "Multiple Instructions": true
  },
  "ReferenceProxy": {
    "Enabled": false
  },
  "ShuffleMembers": {
    "Enabled": true
  },
  "InnerClassRemover": {
    "Enabled": true,
    "Remap": true,
    "Remove Metadata": true
  },
  "NameObfuscation": {
    "Enabled": false
  },
  "Packager": {
    "Enabled": true,
    "Use MainClass from the JAR manifest": true,
    "Main class": "com.jokerkap.MyWorking"
  },
  "FlowObfuscator": {
    "Enabled": true,
    "Mangle Comparisons": true,
    "Replace GOTO": true,
    "Replace If": true,
    "Bad POP": true,
    "Bad Concat": true,
    "Mangle Switches": false,
    "Mangle Return": false,
    "Mangle Local Variables": false
  },
  "HideMembers": {
    "Enabled": true
  },
  "Inlining": {
    "Enabled": false
  }`

Error :

`.... Finished after 528ms
Transforming with 8 threads...
org.objectweb.asm.MethodTooLargeException: Method too large: com/jokerkap/MyWorking.initComponents ()V
        at org.objectweb.asm.MethodWriter.computeMethodInfoSize(MethodWriter.java:2089)
        at org.objectweb.asm.ClassWriter.toByteArray(ClassWriter.java:458)
        at me.superblaubeere27.jobf.JObfImpl.lambda$processJar$6(JObfImpl.java:406)
        at java.lang.Thread.run(Unknown Source)`

Thnx
